### ISSUE TITLE
Socket already registered.

### ISSUE THREAD

**Issue by sbansal6** [kfzteile24/postgresql-proxy#7]
Thanks for writing this library. I am not able to run it. Getting socket already  registered error.
Any help is appreciated.

-- trace
Traceback (most recent call last):
  File "proxy.py", line 198, in <module>
    proxy.listen()
  File "proxy.py", line 149, in listen
    self.accept_wrapper(key.fileobj)
  File "proxy.py", line 107, in accept_wrapper
    self.__register_conn(conn)
  File "proxy.py", line 70, in __register_conn
    self.selector.register(conn.sock, conn.events, data=conn)
  File "/Users/sbansal/.pyenv/versions/3.6.0/lib/python3.6/selectors.py", line 536, in register
    key = super().register(fileobj, events, data)
  File "/Users/sbansal/.pyenv/versions/3.6.0/lib/python3.6/selectors.py", line 241, in register
    .format(fileobj, key.fd))
KeyError: "<socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 5111), raddr=('127.0.0.1', 53688)> (FD 7) is already registered"

**Comment by apisarenco** [comment]
That function, `accept_wrapper` should get called only when an incoming connection is established. It basically gets a new connection socket when it accepts the connection, and then registers it to the selector.

This error shouldn't happen, unless the same socket gets registered twice to the selector.

As I've just ran it locally on a brand new machine, and it worked without me changing either the example config, or anything in the code, I assume that it has something to do either with your modifications (the lines reported in the error are different from the ones in the master branch), or with some local settings or software.

Since I can't replicate it, I'm afraid I'm not much help here.

**Comment by sbansal6** [comment]
Thanks @apisarenco. I was able to get through that error by using a new vm. But now the call gets stuck...

2020-03-26 18:09:15,212 : INFO : Loading module tableau_hll
2020-03-26 18:09:15,270 : INFO : Starting proxy instance
2020-03-26 18:09:15,270 : INFO : listening to 127.0.0.1:5111
2020-03-26 18:09:33,825 : INFO : connection from ('127.0.0.1', 45144), connection initiated proxy_1
2020-03-26 18:09:33,879 : INFO : initiated client connection to dpb-redshift.clzxzuwxkrby.us-west-2.redshift.amazonaws.com:5439 called postgresql
2020-03-26 18:09:33,880 : DEBUG : proxy_1 can receive
2020-03-26 18:09:33,881 : DEBUG : proxy_1 received data:
b'\x00\x00\x00\x08\x04\xd2\x16/'
2020-03-26 18:09:33,881 : INFO : intercepting packet of type 'b''' from proxy_1
2020-03-26 18:09:33,881 : DEBUG : Received message. Relaying. Speaker: proxy_1, message:
b'\x00\x00\x00\x08\x04\xd2\x16/'
2020-03-26 18:09:33,882 : DEBUG : sending to postgresql_1:
b'\x00\x00\x00\x08\x04\xd2\x16/'
2020-03-26 18:09:33,924 : DEBUG : postgresql_1 can receive
2020-03-26 18:09:33,925 : DEBUG : postgresql_1 received data:
b'S'

**Comment by apisarenco** [comment]
This was never tested with Redshift.

It appears that RedShift is sending back a message that consists only of a single byte - `S`. That is unusual and I don't know what to make of it.

https://www.postgresql.org/docs/current/protocol-message-formats.html

The only metions of `S` are either Sync or Parameter Status. Both of them require an additional 4 bytes for the int32 that is the message length. But that message is just not here.

This needs more debugging if it is to work with Redshift. The way I did it was to see what happens between client and server when they normally talk, by using a tools like Wireshark.

https://github.com/kfzteile24/postgresql-proxy/blob/master/connection.py

This file is responsible for handling messages. There are only 3 included cases. 1 that just starts with a 32 bit int, 1 that starts with `N` and doesn't have anything else (like the `S` in this case), and the rest of the cases that have to have an int32 following it. The reason it's not just sending stuff around, is to identify the specific packets and intercept them. The script needs to know where one packet begins and ends.

If you can figure out what is happening here, and program that case in this file, you'll likely make it work.

I don't have any Redshift instances to test it with.

**Comment by sbansal6** [comment]
@apisarenco :- I tried with postgress as well . Same behavior. Hangs on 'S' and then fails (something new). I appreciate you looking into this. I am providing an instance of postgres 9.5 for you to connect

Url:- postgres95.postgres.database.azure.com
database: postgres
user: postgres@postgres95
pwd: Mysignature2

I am also looking into code as we speak. Curious to see if you get the same error while connecting to above instance.

i am able to connect via sql ide (dbeaver.)

![Screen Shot 2020-03-27 at 9 27 12 AM](https://user-images.githubusercontent.com/1934183/77766077-2c662980-700d-11ea-9db1-ef2f4b6a329e.png)

**Comment by sbansal6** [comment]
@apisarenco :- it's working now all IDE's (SQL workbench, dbweaver )

Solution:- Need to add unregister connection when no receive data
added **self.__unregister_conn(conn)** in else block at line 115 in proxy.py

**Comment by apisarenco** [comment]
Care to make it into a pull request?

1. Fork the repository
2. Commit and push your change
3. Issue a pull request
4. I merge it

**Comment by orpheus** [comment]
Thanks @sbansal6 for figuring out that problem, helped me today on the job. @apisarenco I went ahead and made the PR with a few changes that I had to do locally to get your service up and running easily. Thank you btw, the proxy was a great help.
